routes/web.php
<?php
//
///*
//|--------------------------------------------------------------------------
//| Web Routes
//|--------------------------------------------------------------------------
//|
//| Here is where you can register web routes for your application. These
//| routes are loaded by the RouteServiceProvider within a group which
//| contains the "web" middleware group. Now create something great!
//|
//*/
//
Route::get('login' , 'Auth\LoginController@index') ;
Route::post('login', 'Auth\LoginController@authenticate') ;
Route::get('logout' , 'Auth\LoginController@logout') ;
Route::get('users' , 'Auth\LoginController@welcome')->name('user.login');
//
Route::get('/', 'StudentController@index')->middleware('Login');
Route::get('users/search' , 'StudentController@search');
Route::get('users/restore/{id}' , 'StudentController@restore');
////Route::get('/', 'StudentController@index');
Route::resource('students', 'StudentController');
Route::resource('scores' , 'ScoreController');
////Route::get('/', 'StudentController@index');
Route::group(['middleware' => ['Role']], function () {
    Route::resource('specializes','SpecializeController' );
    Route::resource('subjects','SubjectController');
});

app/Specialize.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Specialize extends Model
{
    protected $table = 'specializes';
    protected $fillable = [
        'name_specialize'
    ];
    public $timestamps = false;

    public function user()
    {
        return $this->hasMany('App\User', 'specialize_id', 'id');
    }

    public function getAll()
    {
        return $this->withCount(['user'])->get();
    }

    public function getUserFromSpecialize($id)
    {
        return $this->where('id', $id)->with('user')->first();
    }

}

app/Http/Controllers/SpecializeController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Specialize;
use App\User;
use App\Http\Requests\SpecializeRequest;
use Illuminate\Http\Response;

class SpecializeController extends Controller
{
    protected $user;
    protected $specialize;

    function __construct(
        User $user,
        Specialize $specialize
    )
    {
        $this->user = $user;
        $this->specialize = $specialize;
    }

    /**
     * Display a listing of the resource.
     *
     * @param Request $request
     * @return Response
     */
    public function index(Request $request)
    {
        $specializes = $this->specialize->getAll();
        return view('specialize/index', compact('specializes'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param \Illuminate\Http\Request $request
     * @return Response
     */
    public function store(SpecializeRequest $request)
    {
        $specialize = $this->specialize->create($request->all());
        return response()->json(['message' => $specialize]);
    }

    /**
     * Display the specified resource.
     *
     * @param int $id
     * @return Response
     */
    public function show($id)
    {
        $specialize = $this->specialize->find($id);
        return response()->json([
            'data' => $specialize
        ]);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param int $id
     * @return Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param \Illuminate\Http\Request $request
     * @param int $id
     * @return Response
     */
    public function update(SpecializeRequest $request, $id)
    {
        $specialize = $this->specialize->find($id);
        $specialize->update($request->all());
        return response()->json([
            "data" => $specialize
        ]);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param int $id
     * @return Response
     */
    public function destroy($id)
    {
        $numberStudent = $this->user->countStudentOfSpecialize($id);
        if ($numberStudent > 0) {
            return false;
        } else {
            $delete = $this->specialize->destroy($id);
            return response()->json(["message" => "Xóa Thành Công"]);
        }
    }
}

resources/views/specialize/index.blade.php
@extends('layout.app')
@section('title', 'Quản lý môn học')
@section('content')
    <div class="container mt-3">
        <input class="form-control" id="search" type="text" placeholder="Tìm kiếm..." >
        <button class="btn btn-success btn-search" data-toggle="modal" data-target="#addSpecialize">Thêm mới</button>
        <br>
        <table class="table table-hover table-specialize">
            <thead>
            <tr>
                <th>STT</th>
                <th>Tên chuyên ngành</th>
                <th >Số lương sinh viên</th>
                <th>Hành động</th>
            </tr>
            </thead>
            <tbody id="myTable">
            @foreach($specializes as $specialize )
                <tr class="tr{{$specialize->id}}">
                    <td><strong></strong></td>
                    <td class="td{{$specialize->id}}">{{$specialize->name_specialize}}</td>
                    <td >{{$specialize->user_count}}</td>
                    <td>
                        <a class="btn btn-primary" href="{{asset('subjects/'.$specialize->id)}}" >Môn học</a>
                        <button value="{{$specialize->id}}" class="btn btn-success action edit">Sửa</button>
                        <button value="{{$specialize->id}}" class="btn btn-danger action delete">Xóa</button>
                    </td>
                </tr>
            @endforeach
            </tbody>
        </table>
        <!-- The Modal -->
        <div class="modal fade" id="addSpecialize">
            <div class="modal-dialog">
                <div class="modal-content">

                    <div class="modal-header">
                        <h4 class="modal-title">Thêm mới ngành học</h4>
                        <button type="button" class="close" data-dismiss="modal">&times;</button>
                    </div>
                    <div class="modal-body">
                        <form action="" method="POST" class="form-add">
                            <div class="form-group">
                                <label for="usr">Tên chuyên ngành :<span class="error-name"></span></label>
                                <input type="text" class="form-control" name="name_specialize">
                            </div>
                            <div class="modal-footer">
                                <button type="submit" class="btn btn-success add-specialize">Thêm mới</button>
                                <button type="button" class="btn btn-danger" data-dismiss="modal">Close</button>
                            </div>
                        </form>
                    </div>
                    <!-- Modal footer -->
                </div>
            </div>
        </div>

    </div>
@endsection
@section('LinkJs')
    <script src="{{asset('js/specialize.js')}}"></script>
    {{--        Modal show edit specialize --}}
    <div class="modal fade" id="editSpecialize" tabindex="-1">
        <div class="modal-dialog">
            <div class="modal-content">

                <div class="modal-header">
                    <h4 class="modal-title">Sửa ngành học </h4>
                    <button type="button" class="close" data-dismiss="modal">&times;</button>
                </div>
                <div class="modal-body">
                    <form action="" method="POST" class="form-edit">
                        <div class="form-group">
                            <label for="usr">Tên chuyên ngành :<span class="error-edit-name"></span></label>
                            <input type="hidden" class="form-control id-specialize" name="id">
                            <input type="text" class="form-control input-specialize" name="name_specialize">
                        </div>
                        <div class="modal-footer">
                            <button type="submit" class="btn btn-success edit-specialize">Thay đổi</button>
                            <button type="button" class="btn btn-danger" data-dismiss="modal">Close</button>
                        </div>
                    </form>
                </div>
                <!-- Modal footer -->
            </div>
        </div>
    </div>
@endsection